GET http://127.0.0.1:3000/authors

###

GET http://127.0.0.1:3000/authors/1

###

POST http://127.0.0.1:3000/authors
Content-Type: application/json

{
    "name": {
        "firstName": "Mr.",
        "surname": "Bean"
    }
}

###

GET http://127.0.0.1:3000/books

###

GET http://127.0.0.1:3000/books/1

###

POST http://127.0.0.1:3000/books
Content-Type: application/json

{
    "isbn": "978-1-4842-3714-4",
    "title": "REST API Development with Node.js",
    "category": "Education",
    "authors": [1, 2]//,
    //"releaseYear": 2018,
    //"status": "0"
}