# Get options for authors resource
OPTIONS http://127.0.0.1:3000/authors

###

# Get headers for a single author
HEAD http://127.0.0.1:3000/authors/1

###

# Get authors collection
GET http://127.0.0.1:3000/authors

###

# Get single author
GET http://127.0.0.1:3000/authors/1

###

# Create new author
POST http://127.0.0.1:3000/authors
Content-Type: application/json

{
    "name": {
        "firstName": "Thomas",
        "surname": "Gottschalk"
    }
}

###

# Delete single author
DELETE http://127.0.0.1:3000/authors/3

###

# Get options for books resource
OPTIONS http://127.0.0.1:3000/books

###

# Get headers for a single book
HEAD http://127.0.0.1:3000/books/1

###

# Get books collection
GET http://127.0.0.1:3000/books

###

# Get single book
GET http://127.0.0.1:3000/books/1

###

# Create new book
POST http://127.0.0.1:3000/books
Content-Type: application/json

{
    "isbn": "978-1-4842-3714-4",
    "title": "REST API Development with Node.js",
    "category": "Education",
    "authors": [1],
    "edition": 1,
    "releaseYear": 2018,
    "status": "0"
}

###

# Create new book
POST http://127.0.0.1:3000/books
Content-Type: application/json

{
    "isbn": "978-1-4842-2665-0",
    "title": "Pro RESTful APIs",
    "category": "Education",
    //"authors": [1, 2]//,
    "edition": 1,
    "releaseYear": 2017,
    "status": "0"
}

###

# Update single book (add author)
PATCH http://127.0.0.1:3000/books/1
Content-Type: application/json

{
    "authors": [1, 2]
}

###

# Delete single book
DELETE http://127.0.0.1:3000/books/1